openapi: 3.1.0
info:
  version: 1.0.0
  title: Shops
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
   This is shop app
tags:
  - name: User
    description: User operations
  - name: Shop
    description: Operation with shops
  - name: Order
    description: User operations

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-4-3qmt.onrender.com/
paths:

  /user/user-info:
    get:
      $ref: ../swagger/paths/user/user-info/get.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/user/logout/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/user/login/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml


  /shop:
    get:
      $ref: ../swagger/paths/shop/get.yaml
  /shop/create:
    post:
      $ref: ../swagger/paths/shop/post.yaml
  /shop/{shopId}:
    get:
      $ref: ../swagger/paths/shop/{shopId}/get.yaml
    delete:
      $ref: ../swagger/paths/shop/{shopId}/delete.yaml
  /shop/{shopId}/update:
    put:
      $ref: ../swagger/paths/shop/{shopId}/update/put.yaml

  /shop/{shopId}/statistics:
    get:
      $ref: ../swagger/paths/shop/{shopId}/statistics/get.yaml
  /shop/{shopId}/statistics/{clientId}/goods:
    get:
      $ref: ../swagger/paths/shop/{shopId}/statistics/{clientId}/goods/get.yaml

  /shop/{shopId}/product:
    get:
      $ref: ../swagger/paths/shop/{shopId}/product/get.yaml
  /shop/{shopId}/product/add:
    post:
      $ref: ../swagger/paths/shop/{shopId}/product/add/post.yaml
  /shop/{shopId}/product/{productId}:
    get:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/get.yaml
  /shop/{shopId}/product/{productId}/delete:
    delete:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/delete/delete.yaml
  /shop/{shopId}/product/{productId}/edit:
    put:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/edit/put.yaml
  /shop/{shopId}/product/{productId}/review:
     get:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/review/get.yaml
  /shop/{shopId}/product/{productId}/review/add:
    post:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/review/add/post.yaml

  /shop/{shopId}/product/{productId}/review/{reviewId}:
    delete:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/review/{reviewId}/delete/delete.yaml

    /shop/{shopId}/product/{productId}/review/{reviewId}/edit:
    put:
      $ref: ../swagger/paths/shop/{shopId}/product/{productId}/review/{reviewId}/edit/put.yaml
  /order:
    get:
      $ref: ../swagger/paths/order/get.yaml
  /order/add:
    post:
      $ref: ../swagger/paths/order/add/post.yaml
  /order/{orderId}/delete:
    delete:
      $ref:../swagger/paths/order/{orderId}/delete/delete.yaml
  /order/{orderId}/put:
    put:
      $ref:../swagger/paths/order/{orderId}/edit/put.yaml


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
