openapi: 3.1.0
info:
  version: 1.0.0
  title: Shops
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
   This is shop app
tags:
  - name: User
    description: User operations
  - name: Shop
    description: Operation with shops
  - name: Order
    description: User operations

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-4-3qmt.onrender.com/
paths:

  /user:
    get:
      $ref: ..\swagger\paths\user\user-info\post.yaml
  /auth/logout:
    post:
      $ref: ..\swagger\paths\user\logout\post.yaml
  /auth/login:
    post:
      $ref: ..\swagger\paths\user\login\post.yaml
  /auth/refresh:
    post:
      $ref: ..\swagger\paths\auth\refresh\post.yaml
  /auth/register:
    post:
      $ref: ..\swagger\paths\auth\register\post.yaml
  /auth/reset-pwd:
    post:
      $ref: ..\swagger\paths\user\reset-pwd\post.yaml
  /auth/send-reset-email:
    post:
      $ref: ..\swagger\paths\user\send-reset-email\post.yaml
  /auth/get-oauth-url:
    get:
      $ref: ..\swagger\paths\auth\get-oauth-url\get.yaml

    /shop:
    get:
      $ref: ..\swagger\paths\shop\get.yaml
  /shop/create:
    post:
      $ref: ..\swagger\paths\shop\post.yaml
  /shop/{id}:
    get:
      $ref: ..\swagger\paths\shop\{id}\get.yaml
    delete:
      $ref: ..\swagger\paths\shop\{id}\delete.yaml
  /shop/{id}/update:
    put:
      $ref: ..\swagger\paths\shop\{id}\put.yaml

  /order:
    get:
      $ref:
  /order/add:
    post:
      $ref:
  /order/{id}/delete:
    delete:
      $ref:
  /order/{id}/put:
    put:
      $ref:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
