type: object
required:
  - _id
  - name
  - price
  - category
  - medicine
  - supplier
  - brend
  - rating
  - stock
  - userId
  - shopId

properties:
    _id:
      type: string
      example: 67aa817202c59a4a92629569
    name:
      type: string
      example: aspirin
    price:
      type: number
      example: 90
    category:
      type: string
      example: vitamin
    medicine:
      type: string
      example: some text
    supplier:
      type: string
      example: dddhh aayyz
    brend:
      type: string
      example: farm
    rating:
      type: number
      example: 2
    stock:
      type: number
      example: 10
    userId:
      type: string
      example: 67a676e8396df9b485290ab8
    shopId:
      type: string
      example: 67aa5d900409923fda18e459
    photo:
      description: "Link to product's photo"
      type: string
      format: string
      example: https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg
